baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ACCESS4ALL'
theme = 'access4all'

[params]
  nwo_credit = 'This project is funded by the NWO, grant number VI.Vidi.221R.036'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 20
[[menu.main]]
  name = 'Publications'
  url = '/publications'
  weight = 30
[[menu.main]]
  name = 'Outreach & Media'
  url = '/outreach-media'
  weight = 40

[frontmatter]
  publishDate = ['publishdate', 'pubdate', 'published']
